### ISSUE TITLE
Compare plugin does not work with the last x64 version of Notepad++ (v7.6)

### ISSUE THREAD

**Issue by AleWin32** [pnedev/compare-plugin#184]
The compare plugin does not work with the last version of Notepad++ (v7.6).
Now it does not appear on Plugins menu because this change:

> Change plugin loading method: Remove the legacy plugin loading way and apply only the new plugin loading method.

You can see the Notepad++ changelog here (with that change):
https://notepad-plus-plus.org/download/v7.6.html

Plugin must be modified (it's only a little change) and recompiled to work again.

**Comment by pnedev** [comment]
I know about that, thank you for writing this issue though.
I'll wait a bit so the new approach in finding and loading Notepad++ plugins is fixed because now it is still under development and a lot of debates are going on (https://notepad-plus-plus.org/community/topic/16621/notepad-7-6-new-plugins-admin).

There is no need to re-compile Compare plugin - just move the _ComparePlugin.dll_ and the folder _ComparePlugin_ in the new plugins' place BUT under sub-folder named _ComparePlugin_.
So you'll need to have:
`%LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin.dll`
`%LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin\git2.dll`
`%LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin\sqlite3.dll`

**Comment by Chrissitopher** [comment]
Thanks for the information! Let me just post the correct paths again (as they were not obvious to me):

```
%LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin.dll
%LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin\git2.dll
%LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin\sqlite3.dll
```
The folder name "ComparePlugin\" in the path to git2.dll and to sqlite3.dll is duplicated. Thanks for pointing this out!

**Comment by chcg** [comment]
See https://notepad-plus-plus.org/news/notepad-7.6.1-released.html

> Plugins Admin, which has been added in 7.6 release, was far from being perfect. In version 7.6.1, Plugins Admin is enhanced on several aspects. However, the enhancement could bring some plugins issues for people who update their Notepad++, due to the new location for plugins. Sorry for the inconvenient. 
> 
> In order to remedy this problem, after the update, if you update from 7.6 :
> Move all %LOCALAPPDATA%\Notepad++\plugins\ (except "Config" folder) to %PROGRAMDATA%\Notepad++\plugins\.

**Comment by OsakaWebbie** [comment]
Hmm, still not working for me. In my case I have the PortableApps version of N++ (currently v. 7.6.3 - I don't know when I upgraded), so the path to `plugins` is `...PortableApps/Notepad++Portable/App/Notepad++/plugins`, but that should be okay, right? When I noticed that Compare was missing from the Plugins menu (just Compare; my other plugins still show), I selected Plugins Admin and told it to install Compare. It appears to have done everything right - all the files mentioned above are where I think they should be, and the file timestamps are Apr. 7, 2017, so they should be the newest ones. But after N++ restarted, I still not see Compare on the Plugins menu, and even weirder, now the Plugins Admin menu item itself has also disappeared (probably unrelated to your plugin, but it means I can't check what the app thinks the plugin status is).

**Comment by pnedev** [comment]
Strange...

Do you now have `ComparePlugin.dll` under `...PortableApps/Notepad++Portable/App/Notepad++/plugins/ComparePlugin` ?

Are you sure you are starting `...PortableApps/Notepad++Portable/App/Notepad++/notepad++.exe` ?

**Comment by OsakaWebbie** [comment]
> Do you now have `ComparePlugin.dll` under `...PortableApps/Notepad++Portable/App/Notepad++/plugins/ComparePlugin` ?

No, the dll is in `plugins`, not the subfolder. Here is a screenshot combo showing the two folders:

![compareplugin location](https://user-images.githubusercontent.com/4035163/52348775-7c300d00-2a68-11e9-8b39-196f18ba5a59.png)

> Are you sure you are starting `...PortableApps/Notepad++Portable/App/Notepad++/notepad++.exe` ?

Just now I tested that. In DirectoryOpus I tested double-clicking your suggested path (`...PortableApps/Notepad++Portable/App/Notepad++/notepad++.exe`) and the higher level .exe (`...PortableApps/Notepad++Portable/Notepad++Portable.exe`). I get the same result as starting it from the PortableApps launcher. Here's a screenshot of the Plugins menu:

![plugins menu](https://user-images.githubusercontent.com/4035163/52348807-8eaa4680-2a68-11e9-8795-1e104af2f5da.png)

I don't have an installed version - there is no folder starting with "N" in either `C:\Program Files` or `C:\Program Files (x86)`. And I always start it from the PortableApps launcher anyway, so even if I did have another copy lurking somewhere, I would never invoke it.

**Comment by pnedev** [comment]
OK then,

Make folder named `ComparePlugin` in `...PortableApps/Notepad++Portable/App/Notepad++/plugins/` and then put `ComparePlugin` folder (containing `git2.dll` and `sqlite3.dll`) and the `ComparePlugin.dll` inside it.

Your final goal is to have:

`...PortableApps/Notepad++Portable/App/Notepad++/plugins/ComparePlugin/ComparePlugin.dll`
`...PortableApps/Notepad++Portable/App/Notepad++/plugins/ComparePlugin/ComparePlugin/git2.dll`
`...PortableApps/Notepad++Portable/App/Notepad++/plugins/ComparePlugin/ComparePlugin/sqlite3.dll`

Restart Notepad++ and check again.

**Comment by MetaChuh** [comment]
i believe this issue can be closed.

ComparePlugin loads without any issues on 7.6.6, if installed via plugins admin, or manually deployed to the correct folders.

many thanks and best regards.

**Comment by pnedev** [comment]
You are right @MetaChuh .
I kept it for a while as a reference for the users with the same problem but I suppose it is not needed anymore.
Thanks.

BR

**Comment by bigrobshag** [comment]
> Thanks for the information! Let me just post the correct paths again (as they were not obvious to me):
> 
> ```
> %LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin.dll
> %LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin\git2.dll
> %LOCALAPPDATA%\Notepad++\plugins\ComparePlugin\ComparePlugin\sqlite3.dll
> ```
> 
> The folder name "ComparePlugin" in the path to git2.dll and to sqlite3.dll is duplicated. Thanks for pointing this out!

I found out that NPP is expecting ComparePlugin.dll also in Path \ComparePlugin\
"C:\Program Files\Notepad++\plugins\ComparePlugin\ComparePlugin.dll" additional to the two others git2.dll and sqlite3.dll.
Used Sysinternals ProcMon to find out - after I took several tries following the boards proposals...
