### ISSUE TITLE
does not find the optimal moved line

### ISSUE THREAD

**Issue by bennoordzij** [pnedev/compare-plugin#239]
I would expect that compare would see the line "Frankrijk, Alpen (41)" as deleted and "Frankrijk, Elzas (139)" as changed
![image](https://user-images.githubusercontent.com/65396636/82038336-af1d7380-96a3-11ea-9aeb-4b89995f1248.png)
Tried to dig into the code myself, but it was too hard to find the "moved lines" part in sources without comments....

Regards, Ben
[Cas stand 20200415.txt](https://github.com/pnedev/compare-plugin/files/4633677/Cas.stand.20200415.txt)
[Cas stand 20200127.txt](https://github.com/pnedev/compare-plugin/files/4633680/Cas.stand.20200127.txt)

**Comment by Yaron10** [comment]
@bennoordzij,

This is fixed in the ComparePlus development version.

![תמונה](https://user-images.githubusercontent.com/10229320/82049677-62e02c80-96bf-11ea-951a-3880b48f57d8.png)
***
Hello Pavel,

I hope you're doing well and in good health. :)

BR

**Comment by pnedev** [comment]
Hi @bennoordzij ,

I know what you mean, this is a known short-coming in Compare plugin.
The good news is that (as Yaron mentioned) the changed decision approach is changed in the new plugin I'm about to release - ComparePlus. I hope to find time to do that soon but thats pretty hard for me currently. Thanks for reporting this anyway.

Hi @Yaron10 ,

Good to 'hear' from you again, friend :)
Thank you for helping. I'm good thanks, just extreemly busy recently.
You 'sound' good as well, I hope it is really that way :)

Best wishes

**Comment by Yaron10** [comment]
Hello my friend Pavel,

I'm glad to learn that you are OK. One can wonder and worry in these days.
I hope your "busyness" is enjoyable. :)

I'm fine as well, thank you.

BR

**Comment by bennoordzij** [comment]
Hi @Yaron10 and @pnedev ,
thanks for the new compare 2.0.0, it really helps me with my different projects.
I still see non-optimal behaviour in the compares, though....
![image](https://user-images.githubusercontent.com/65396636/84565723-683aa080-ad6b-11ea-9df4-bfe72a76567d.png)
and
![image](https://user-images.githubusercontent.com/65396636/84565749-94eeb800-ad6b-11ea-89b7-149ff6897acb.png)

Not that these issues are blocking, but to let you know...

Regards and stay healthy, 
Ben
[Cas stand 20200612.txt](https://github.com/pnedev/compare-plugin/files/4774377/Cas.stand.20200612.txt)
[Cas stand 20200127.txt](https://github.com/pnedev/compare-plugin/files/4774378/Cas.stand.20200127.txt)

**Comment by Yaron10** [comment]
Hello @bennoordzij,

Your issues are fixed in the new **ComparePlus** development version. **Not in ComparePlugin v2**.
(Pavel, the developer, has been busy recently and therefore the official release of ComparePlus is delayed).

- Download ComparePlus.dll [here](https://github.com/pnedev/compare-plugin/issues/233#issuecomment-620061843). 
- Rename the `ComparePlugin` folder under `plugins` to `ComparePlus`.
- Delete the old ComparePlugin.dll.
- Paste the ComparePlus.dll into the newly renamed folder `ComparePlus`.

- Rename also the `ComparePlugin` folder under `plugins\ComparePlus` to `ComparePlus`.

- Start NPP. You'd have to re-apply your settings as a new INI file is created.

See also https://github.com/pnedev/compare-plugin#installation.

Best regards.

**Comment by pnedev** [comment]
Hi @Yaron10,

Thanks for helping. I appreciate it as always. :)

@bennoordzij,

Yaron really said it all.
You either need to wait for the official release of ComparePlus (the new plugin) or use its development version.

Unfortunatelly I cannot say for sure when the final version will be ready.

BR

**Comment by pnedev** [comment]
Implemented/fixed and will be included in the first ComparePlus plugin release coming in a month or so.
