### ISSUE TITLE
Enable/Disable Toolbar Buttons

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#39]
Hello Pavel,

If the Customize Toolbar plugin is not installed, the Compare's toolbar buttons are always enabled.
I think it's important to address this issue (especially now that you enable/disable the commands much more frequently).

If the Customize Toolbar plugin IS installed, there's a problem which is probably related to that plugin.
Still, please have a look.

STR:

Open three files.
Compare.
Activate the third not-compared file.
Activate the compared file *at bottom*.

Result:

The Compare's toolbar buttons are disabled.

NOTE: If you open a menu and move to another one (e.g. press File and move to Edit), the buttons' state is updated.

Thank you.

BR

**Comment by pnedev** [comment]
Oh, is that the case?
I haven't noticed that as I'm using the Customize toolbar plugin.
I'll certainly check that, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Thank you. I appreciate that.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

A related minor issue:
If you "Set first" and then close the selected file, "Clear" should be disabled.

Thank you.

BR

**Comment by pnedev** [comment]
I'll look into this, thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The "Set first" issue when the file is closed is fixed. Thanks for catching that.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I appreciate it.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

The N++ toolbar CP buttons state issue is fixed, thanks for reporting.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Special thanks. CP is getting better and greater *by the day*. :+1:  
Judging by the time-frame, I assume you haven't corresponded with Dave. :)

The navigation buttons state works like a charm.
I still have a problem with "Clear Active Compare" which I've added with CT.
May I ask you to add it to CP code when you have some free time? I'd appreciate that.

BTW, is "Clear All Compares" intentionally always enabled?

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

You are welcome.

> BTW, is "Clear All Compares" intentionally always enabled?

Yes, it is. I'll think about disabling it some time in the future.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks again. I appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. It works like a charm. :+1: 

BR
