### ISSUE TITLE
Diff since last Save: File and EOL formats

### ISSUE THREAD

**Issue by Yaron10** [pnedev/compare-plugin#70]
Hello Pavel,

Thanks again for fixing and restoring this feature.

If the compared file uses a certain format (e.g. Windows-1255 Hebrew) and your default new file is UTF-8, you get many false diffs.
Would it be possible to open the new file in the compared file's format?
And what about EOL format?

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

> Would it be possible to open the new file in the compared file's format?

Hm, I thought I was doing so. I'll test that again.
The EOL is a good idea, I'll implement that, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I do appreciate it.

BR

**Comment by pnedev** [comment]
Hello Yaron,

After a quick test it seems the EOL format doesn't matter.
It seems CP ignores EOL when comparing. This issue aside, it might be something that needs fixing.
I'll need to test more.

I believe I'm currently setting the new file encoding to the temp file.
Can you give me the steps to reproduce the issue you are facing?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for great work.

Could you please modify the second line in [this](https://github.com/pnedev/compare-plugin/files/279603/Test.zip) file (Windows-1255) and "Diff since last Save"?

BR

**Comment by xylographe** [comment]
Hello Yaron,

Indeed, the temp file is UTF-8 encoded.

**Comment by xylographe** [comment]
Also, wrong EOL in blank lines, causing the ''Dos/Windows" in the status line.

![cp-ls1](https://cloud.githubusercontent.com/assets/8535293/15512254/38746a96-21df-11e6-88c0-a40ab0fa22cb.png)

**Comment by Yaron10** [comment]
Hello xylographe,

Thanks for testing and confirming.

BTW, what does the L (within the circle) stand for?

BR

**Comment by xylographe** [comment]
Hello Pavel,

> what does the L (within the circle) stand for?

- **Ⓛ** : Last Saved
- **Ⓢ** : svn
- **Ⓖ** : git
- **Ⓑ** : Base (Old)
- **Ⓕ** : Focal (New)

It takes little space in the tab bar, yet stands out, because I wouldn't use circled letters in a file name.
Ideally, the circled letters should be displayed in bold (or perhaps even black) weight, if that would be possibly in a tab caption.

**Comment by pnedev** [comment]
Hello @xylographe ,

Good idea.
However I think full text is more descriptive than those symbols.
Unfortunatelly, tab text cannot be made bold either (as far as I know).

BR

**Comment by pnedev** [comment]
Hello,

Fixed in latest master. Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I was impressed.
***
With your permission, two questions:

1) I've just noticed the "Last Save" addition to the temp-file's name (shame on me).
That's *really nice*. Any reason not to use `** Last Save` as in Set First?
(I'm pretty sure I would have noticed it had `**` been used :) ). 

2) The user can manually toggle the "Read Only" flag. 
I don't see any problem in it; on the contrary. Your opinion?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> (I'm pretty sure I would have noticed it had ** been used :) )

As a matter of fact it had been using `**` before the fix ;)

I'm saving a bit of coding this way as now the tab name is actually a real file name.
Do you think it will be better to use `**` variant?
@xylographe , what do you think?

> I don't see any problem in it; on the contrary. Your opinion?

Well, it is a problem as this file is supposed to be unchangeable - it is already in the history and does not have any effect - changing it leaves the false impression that it actually has a meaning and some real effect but it doesn't. However, I cannot stop the user from finding some clever way to circumvent the change protection no matter how hard I try (well, perhaps I can but don't tell anybody ;)
As an additional protection I can make the file with read-only attribute but that can be changed by the user as well.

BR

**Comment by xylographe** [comment]
Thank you, Pavel. Text encoding and EOLs  work just fine:

![cp-ls2](https://cloud.githubusercontent.com/assets/8535293/15569225/503b398c-2330-11e6-9dbe-bbe72bdefe3c.png)

As you can see the change from **` ** `** to **`_`** doesn't really affect me. ;)
Only the full file name in the window frame is slightly affected—apparently the window title is not Unicode compliant, and the **Ⓛ** is displayed as a question mark, which won't kill me. :)

However, I think you could replace **` ** `** with something that is not prohibited in a Windows file name. Perhaps, **` ## `** or **`¤¤`**? IMO it is important to use the *same* mark separator for "New/Old to Compare", "Last Save", "Svn", and "Git".

I think, the read-only status is enough. If a user changes it despite the "Last Save" mark, it is their own responsibility. Anyway, it won't do any harm, because the temp file will be deleted. It's just a bit odd that NPP asks if it should save the temp file, when its content is modified.

**Comment by pnedev** [comment]
Hello @xylographe ,

Thanks for the feedback.

> IMO it is important to use the same mark separator for "New/Old to Compare", "Last Save", "Svn", and "Git".

I have made the mark in the tab bar to resemble "New/Old to Compare" - `**`.

> apparently the window title is not Unicode compliant

I didn't get that. Could you elaborate more?

> It's just a bit odd that NPP asks if it should save the temp file, when its content is modified.

I have fixed that in case you clear compare. If you manually close a modified temp file it is not possible and you'll get the _save-modified_ dialog.

Thank you.

@Yaron10 ,

If you can think of something else or you have other suggestions regarding this issue - any comments are welcome. Thanks.

Just FYI - When you are in a diff compare mode and you move the temp file it will remain open in N++ but the temp file itself will be deleted. I'll think how I can fix that.

And one last thing - If you have triggered "Last Save Diff" and you trigger it again for the same file you will get "File is already being compared". The logical thing would be to re-compare. Now re-compare is possible if you just make a regular compare (as the original and temp files are in separate views).
This also needs fixing, what do you guys think?

BR

**Comment by xylographe** [comment]
Hello Pavel,

> I have made the mark in the tab bar to resemble "New/Old to Compare" - ` ** `.

Thank you. This consistency among CP tab marks is certainly worth the extra C++ code.

> \[quoting myself] apparently the window title is not Unicode compliant

Non-ansi characters (like the circled L) are displayed as question marks in the dialogue caption (window title). In the image above `Test.css ?` instead of `Test.css Ⓛ`. Obviously, not a CP issue.

> "File is already being compared"

IMO that is expected behaviour. You cannot start a second "Last Save diff", but you can edit the unsaved tab and re-compare.

**Comment by pnedev** [comment]
Hello @xylographe ,

Thank you for the clarification and the feedback.

BR

**Comment by Yaron10** [comment]
Hello Pavel and xylographe,

> As a matter of fact it had been using ** before the fix ;)

When I first read this I thought to myself: "One of those good lessons to life." :)

> I have made the mark in the tab bar to resemble "New/Old to Compare" - **.

But now I'm confused. I still get `_LastSave` and not `**`.
***

> Well, it is a problem as this file is supposed to be unchangeable

Actually, why?
Theoretically this can be a user-preference. Some users may prefer to save the new file (in the original file folder - in order not to complicate things even more).
I'm not suggesting it because IMO the [Undo list is emptied after Compare](https://github.com/pnedev/compare-plugin/issues/57) issue is *major* in "Diff since last Save" (the file is modified by definition), and therefore the extra work on this feature is not worth it. 

You may consider what seems to me not as complex:
If the user toggles the "Read Only" flag, modifies the file and then chooses to save it - *do not delete it* and let it be saved in the temp folder.

This would not solve the "it is already in the history and does not have any effect" issue if the temp file is not modified and saved.
You can remove it from the Recent Files List but you have a [similar issue](https://github.com/pnedev/compare-plugin/issues/19) in every Compare.

> However, I cannot stop the user from finding some clever way to circumvent the change protection no matter how hard I try (well, perhaps I can but don't tell anybody ;)

Well, a bird has spread the word. :)
As you understand.
***
> Just FYI - When you are in a diff compare mode and you move the temp file it will remain open in N++ but the temp file itself will be deleted. I'll think how I can fix that.

The problem is that temp file remains open in NPP and not discarded as the Compare is cleared. Correct? 

> And one last thing - If you have triggered "Last Save Diff" and you trigger it again for the same file you will get "File is already being compared". The logical thing would be to re-compare. Now re-compare is possible if you just make a regular compare (as the original and temp files are in separate views).
> This also needs fixing, what do you guys think?

In principle I don't see a reason not to allow a second "Last Save Diff" but I suppose that changing this behavior would also require a lot of work.

Thank you.
BR

**Comment by xylographe** [comment]
Hello Yaron,

> But now I'm confused. I still get _LastSave and not **.

```
PS> git grep -F ' ** '
src/Compare.cpp:677: _sntprintf_s(tabText, _countof(tabText), _TRUNCATE, TEXT("%s ** %s to Compare"),
src/Compare.cpp:880: _sntprintf_s(tempFile, _countof(tempFile), _TRUNCATE, TEXT("%s ** %s"), fileName, nameMark);
```
Are you using current version?

A temporary file, should not be permanent. In fact, it will be overwritten when you perform another "Last Save diff" on the same file later on. But you can of course use the regular NPP "Save Copy".

**Comment by xylographe** [comment]
Hello Pavel,

A repeated "Last Save diff" *might* be useful in this situation:

1. trigger "LS diff"
2. some editing
3. save file
4. some more editing
5. trigger "LS diff" to diff current buffer against save from step 3

This would make sense because of (3).

**Comment by Yaron10** [comment]
Hello xylographe,

> Are you using current version?

Yes, I am.
I've figured it out: change "Old file position" to "Right/Bottom" and you get `_LastSave`.

> A temporary file, should not be permanent. In fact, it will be overwritten when you perform another "Last Save diff" on the same file later on. But you can of course use the regular NPP "Save Copy".

This is the question: why must it be temporary?
If you're referring to the *temp folder* - well, that's a good point. However, if this option (Save) is not offered by CP but rather the user "hacks" it and wants to save the file, the temp folder might be acceptable.

> A repeated "Last Save diff" might be useful in this situation:
> ... 

This can be achieved with Compare. Or am I missing anything?
Again, In principle I don't see a reason not to allow a second "Last Save Diff".

Thank you.
BR

**Comment by Yaron10** [comment]
> This can be achieved with Compare. Or am I missing anything?

Sorry. Responded too fast.
Good point.

**Comment by Yaron10** [comment]
Hello Pavel,

> However, I cannot stop the user from finding some clever way to circumvent the change protection no matter how hard I try (well, perhaps I can but don't tell anybody ;)

Disable the "Set as Read Only" command when the temp file gets the focus?

Thank you.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

STR:
Activate a saved file.
Diff since last Save.

Result:
Files match.

Expected:
File X is saved - operation ignored.

*

One more point:
The user clears the Read Only flag and modify the temp file.
Diff since last Save (when the temp file is active).

Regard it as "Diff since last *other file* Save" or not allow it?
The latter seems right.

Thank you. 
BR

**Comment by pnedev** [comment]
Hello @Yaron10 ,

> I've figured it out: change "Old file position" to "Right/Bottom" and you get _LastSave.

I have fixed that, thanks for catching it and investigating.

> If the user toggles the "Read Only" flag, modifies the file and then chooses to save it - do not delete it and let it be saved in the temp folder.

Why would that be useful? It is merely a temp file. Besides, @xylographe is right - one can always use the "Save As" command.

> The problem is that the temp file remains open in NPP and not discarded as the Compare is cleared. Correct?

Yes. And N++ will at some point ask if you want to keep the file data in it (as the temp file will actually be deleted).

> Disable the "Set as Read Only" command when the temp file gets the focus?

Doesn't seem necessary to me. Just adding more complications.

About the STR:

> Expected:
File X is saved - operation ignored.

I have deliberately done that because of the "Clear Undo on Compare" behavior.
If you "Last Save Diff" then clear the compare the undo info is cleared. Now although the file looks modified (red save icon in the tab) the Scintilla command to check the "doc is dirty" status relies on the undo list presence and thus cannot be used reliably. This leads to false "File X is saved" message on second "Last Save Diff". Maybe I can find a better way of checking that a file is dirty than Scintilla command, then I will bring back the "File X is saved" message.

> One more point:
The user clears the Read Only flag and modifies the temp file.
Diff since last Save (when the temp file is active).

That's an interesting case. I'll look into this soon.

Thank you for all the testing and for the suggestions.

Hello @xylographe ,

Regarding this:

> A repeated "Last Save diff" might be useful in this situation:

I was thinking of auto-clearing the "Last Save Diff" compare on new file save.
What do you guys think about that?

Thank you for the suggestion.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Regard it as "Diff since last other file Save" or not allow it?
The latter seems right.

This shouldn't be allowed. And at the moment it is forbidden - you'll get "File already compared" message.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> I've figured it out: change "Old file position" to "Right/Bottom" and you get _LastSave.
> 
> I have fixed that

Great. Thank you very much.

Two minor comments:
1) Wouldn't "Last Save" (with a space; in the tab bar) resemble the command?
2) In "First to Compare" you don't change the window title. Does changing it in this case save some code?
***
> If the user toggles the "Read Only" flag, modifies the file and then chooses to save it - do not delete it and let it be saved in the temp folder.
> 
> Why would that be useful? It is merely a temp file. Besides, @xylographe is right - one can always use the "Save As" command.
> ...
> ...
> Disable the "Set as Read Only" command when the temp file gets the focus?
>
> Doesn't seem necessary to me. Just adding more complications.

Those were not requests. You asked for "other suggestions regarding this issue" and I thought you referred to the "Read Only" question as well.

So you'd rather keep the current behavior (allowing the user to change the "Read Only" flag but not really save the file)? 
This is absolutely fine. Just a minor known-issue if the file is saved. :) 
***
> I have deliberately done that because of the "Clear Undo on Compare" behavior.
> If you "Last Save Diff" then clear the compare the undo info is cleared.

I see. Thanks for the explanation.
One comment: the wrong file is active when the "Files Match" message is displayed in this case. :)
***
> Regard it as "Diff since last other file Save" or not allow it?
> The latter seems right.
> 
> This shouldn't be allowed. And at the moment it is forbidden - you'll get "File already compared" message.

This point was raised in case you would change the current behavior and allow a re-Last Save.
***
> I was thinking of auto-clearing the "Last Save Diff" compare on new file save.

I can see the logic behind it but I think it's not the expected behavior and the user might wonder about it.

Best regards.

**Comment by xylographe** [comment]
Hello Pavel,

> I was thinking of auto-clearing the "Last Save Diff" compare on new file save.

Like Yaron, I think, that this could/would be confusing. It certainly is not what I would prefer. After editing the current file (Scintilla buffer), I would like to be able to save that modified buffer, yet keep the diffs against the older save (in temp file) to continue editing.

However, at some point I might want to replace the temp file with the new last saved contents. ATM this is possible with "Clear Compare" + "Last Save diff". Perhaps, the "Clear Compare" could be made implicit, similar to the implicit "Clear Compare" when re-comparing?

So, Alt-D would re-compare current (Scintilla buffer) with initial last save (temp file), while Alt-L would start a new "Last Save diff" between current and new last save (assuming, of course, that NPP "Save" has been triggered since the initial last save).

**Comment by pnedev** [comment]
Hello Yaron and xylographe,

Yaron,

> Two minor comments:
1) Wouldn't "Last Save" (with a space; in the tab bar) resemble the command?
2) In "First to Compare" you don't change the window title. Does changing it in this case save some code?

Done, thanks.

> So you'd rather keep the current behavior (allowing the user to change the "Read Only" flag but not really save the file)?

I don't think it is a problem, yes.
I'll consider disabling the "Set Read-only" N++ command in the menu, thank you.

> One comment: the wrong file is active when the "Files Match" message is displayed in this case. :)

This is fixed, thanks.

Yaron and xylographe,

> I can see the logic behind it but I think it's not the expected behavior and the user might wonder about it.
Like Yaron, I think, that this could/would be confusing.

You are right, I agree.

xylographe,

> However, at some point I might want to replace the temp file with the new last saved contents. ATM this is possible with "Clear Compare" + "Last Save diff". Perhaps, the "Clear Compare" could be made implicit, similar to the implicit "Clear Compare" when re-comparing?

What about keeping "Diff since Last Save" not usable (if it has already been triggered and is still active) but if you save the file and use a normal compare to update the LastSave temp file and make the new diff?

Thank you both.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Disabling "Diff since Last Save" until the user triggers "Clear Compare" would be fine.

Automatically updating the LastSave temp file to the most recent (real) LastSave is exactly what I would like to avoid. I want to be able to keep re-comparing to the unchanged temp file (the initial LastSave) until I decide I'm finished, even if I have created a new LastSave file (by saving the file after editing).

I don't want to start a new "Diff since Last Save" by triggering "Compare". Remember, that you wanted "Compare" <=> "Diff"? Which turns out to be yet another good decision, :) and IMO the separation between "Compare" and "Diff" should remain consistent: triggering "Compare" should never initiate any kind of "... Diff ...".

**Comment by pnedev** [comment]
Hello @xylographe ,

Good point.
Then your idea is:

1) If you have active "Last Save diff"
2) And you have saved the file
3) Allow directly new "Last Save diff" that will implicitly clear the current one.

? Thanks.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Yes, if it is not to much work, that would be ideal.
But, if it is more convenient to you, I wouldn't mind the alternative: disable "Diff since Last Save" until explicit "Clear Compare".

**Comment by pnedev** [comment]
OK @xylographe , thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel and xylographe,

> 1) Wouldn't "Last Save" (with a space; in the tab bar) resemble the command?
> 2) In "First to Compare" you don't change the window title. Does changing it in this case save some code?
> 
> Done, thanks.

Thank you.
The window title is still changed. Not a problem at all. Just to make sure.

> One comment: the wrong file is active when the "Files Match" message is displayed in this case. :)
> 
> This is fixed, thanks.

Great. Thank you very much.

> So you'd rather keep the current behavior (allowing the user to change the "Read Only" flag but not really save the file)?
> 
> I don't think it is a problem, yes.
> I'll consider disabling the "Set Read-only" N++ command in the menu, thank you.

Thanks.
***
> Then your idea is:
> 
> 1) If you have active "Last Save diff"
> 2) And you have saved the file
> 3) Allow directly new "Last Save diff" that will implicitly clear the current one.

I'd like to make sure I understand that correctly.

By "you have saved the file" you mean the original one (not the temp), correct?
- And if the temp file is active and you trigger "Diff since Last Save"?

If the original file has not been saved again, "Diff since last Save" would not be allowed (or disabled)?
- In a regular Compare you allow re-Compare even if the files have not been modified. Why not allow it here?

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Could you clarify

> The window title is still changed. Not a problem at all. Just to make sure.

?
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

When you activate the temp file, you still get "_LastSave" in the window title.
http://s33.postimg.org/hac4sunvz/image.png

> Good point, thanks.

I'm glad you agree. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

I see now what you mean (literally).
Yes, this is normal. This is the real temp file name. It cannot have symbols like '*'.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I understand that.
But why add "_LastSave" to the temp file mane?
In case the original file was also located in the temp folder?

Thank you.
BR

**Comment by Yaron10** [comment]
Hello again Pavel,

And what happens if the original file name consists of the max-chars allowed?

Thanks.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> But why add "_LastSave" to the temp file mane?

Because the reported names in the Progress dialog and in case the files match is the file name (without the path).
Also because you might not be using the tabs at all (_Hide Tabs_ from _Settings_) - you might be using the Document List Panel. And the Doc panel shows only the file names.

> And what happens if the original file name consists of the max-chars allowed?

Big trouble :)
The temp file that is created will have the name that fits the max-chars (whatever that is).
But that is also true for the whole CP code as MAX_PATH is used everywhere throughout the code.
I think N++ API now also uses MAX_PATH.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for the explanation.

> Because the reported names in the Progress dialog and in case the files match is the file name (without the path).
> Also because you might not be using the tabs at all (Hide Tabs from Settings) - you might be using the Document List Panel. And the Doc panel shows only the file names.

I often compare two files bearing the same name and located in different folders.

> The temp file that is created will have the name that fits the max-chars (whatever that is).

You mean it should be truncated if the original already contains max-chars?

BR

**Comment by pnedev** [comment]
Hello Yaron,

> I often compare two files bearing the same name and located in different folders.

That's OK.
Another reason is that this way you know the source of the temp file - is it coming from the Git repo or it is the last saved state.. etc.

> You mean it should be truncated if the original already contains max-chars?

No. It will be truncated if the `temp_folder_path + original_file_name + temp_mark > MAX_PATH`.
It will be truncated to MAX_PATH chars if that is true.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Another reason is that this way you know the source of the temp file - is it coming from the Git repo or it is the last saved state.. etc.

Good point.

> It will be truncated if the temp_folder_path + original_file_name + temp_mark > MAX_PATH.

That's what I meant. :)

Thanks again.
BR

**Comment by xylographe** [comment]
Hello Pavel,

> Why not allow re-compare always then (for all the 'diff' commands)?

(1) open file
(2) edit (modify)
(3) trigger "Diff since Last Save" (temp file == Last Save)
(4) edit
(5) file > save (temp file != Last Save)
(6) trigger "Compare"

Should re-compare buffer and temp file.

(7) trigger "Diff since Last Save"

Ideally, should be ignored because buffer == Last Save (step 5).

(8) edit (buffer != Last Save)
(9) trigger "Diff since last Save"

Because buffer != Last Save, the current buffer-to-temp-file compare would be cleared (and the temp file deleted). Then the new "Diff since last Save" is performed.

For Git things might be more complicated, because you don't know if the index has changed (e.g., `git add`), which would be similar to an external modification of Last Save.

**Comment by pnedev** [comment]
Hello @xylographe ,

> Ideally, should be ignored because buffer == Last Save (step 5).

Why ignore that? The user sees that the file is not changed (the tab icon is not red but blue). Yet he triggers "Diff since Last Save" -> OK, that's perfectly valid -> compare and report that the new "Diff since Last Save" is equal.

I think that if the user triggers "Compare" on already active diff command result we should re-compare against the current temp file.
If we trigger the same diff command then it should redo the diff.
If we trigger other diff command we should report "File is already compared - ignore".

BR

**Comment by xylographe** [comment]
Hello Pavel,

> The user sees that the file is not changed (the tab icon is not red but blue).

The 'dirty' status is not always correct (e.g., ignored external file modification).
But, for argument's sake, let's disregard such exceptional situations.

> compare and report that the new "Diff since Last Save" is equal.

But then the active "Diff since Last Save" will have been cleared, while there are no new diffs to replace it. The actual result will be an implicit "Clear Compare" and a failed "Diff since Last Save". Ideally, the implicit "Clear Compare" should only be performed if the new "Diff since Last Save" will succeed.

However, there is probably no way to tell beforehand if "Diff since Last Save" is going to succeed.
This leaves us with two options:
(1) current behaviour: "File X is already compared - operation ignored"
(2) clear active compare, then attempt new "Diff..." regardless of the outcome

With (1) the user is forced to decide if they want to trigger an explicit "Clear Compare". This could be regarded as the less convenient option.
With (2) the outcome might not be what the user intended, yet they cannot go back (undo), because the temp file with the initial save has been removed. This could be regarded as the option that requires the user to remain focused.

ATM I'm not sure which of these two I prefer.

> I think that if the user triggers "Compare" on already active diff command result we should re-compare against the current temp file.

Agreed.

> If we trigger other diff command we should report "File is already compared - ignore".

Agreed.

> If we trigger the same diff command then it should redo the diff.

Indecisive.  Time-out called! :)

**Comment by xylographe** [comment]
Hello Yaron,

> I often compare two files bearing the same name and located in different folders.

This is a problem ATM,
(1) open files `a\x.txt` and `b\x.txt` in NPP
(2) modify `a\x.txt`
(3) trigger "Diff since Last Save"
(4) modify `b\x.txt`
(5) trigger "Diff since Last Save"

Result: the `a\x.txt` diff is gone, and NPP informs us that the (theoretically immutable) temp file has changed. Problem is that both diffs create a temp file with the same name.

**Comment by pnedev** [comment]
Hello @xylographe ,

That was a good point - your comment to Yaron's answer.
I have fixed that - now the new temp file name will be added an index if such file already exists.
Thanks for catching that.

About the diff - I'll leave it to the user for now. If he decides to redo the diff he will be forced to explicitly clear the current. Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel and xylographe,

Some busy days. I'll reply tomorrow.

Thank you.
BR

**Comment by xylographe** [comment]
Hello Pavel,

Thank you for fixing the "identical temp file name" issue.

Is it technically possible to instruct NPP not to add the temp files to the Recent Files list?

Do you already know that the "SVN diff" temp file has the 'wrong' EOL (`\r\n` in original, `\n` in temp file), or should I open a new issue?

"Git diff" reports "Missing Git data." Does this reflect the current state of affairs (implementation not yet finished) or is there a problem at my end?

**Comment by pnedev** [comment]
Hello guys,

Yaron, no problem, take your time.

xylographe,

> Is it technically possible to instruct NPP not to add the temp files to the Recent Files list?

I don't think so but I haven't investigated this yet. As I wrote to Yaron some time ago, I don't use the Recently Closed list so I am not noticing the side effects CP causes. I will look at this. It seems an important issue to both of you so perhaps it will be important issue for everyone.
However I'm not sure this can be avoided.

> Do you already know that the "SVN diff" temp file has the 'wrong' EOL (\r\n in original, \n in temp file), or should I open a new issue?

I didn't know. Please file a new issue.

> "Git diff" reports "Missing Git data." Does this reflect the current state of affairs (implementation not yet finished) or is there a problem at my end?

"Git diff" should be working fine. At least I haven't noticed problems so far.

Thanks.

BR

**Comment by xylographe** [comment]
Hello Pavel,

Problem with "Git diff" – my `.git` directories are actually files created by `git init --separate-git-dir`.
Content example,  (one line terminated by `\n`)
```
gitdir: //cardea/xg/Repos/NppComparePlugin
```

Recently Closed list – yes, it is quite annoying to have to remove the temp files manually.

**Comment by pnedev** [comment]
Hello @xylographe ,

OK, got it.
Could you create new issues for SVN EOL, Git path and Recent List?
This issue is becoming a discussion thread and I don't want to miss an important issue in the 'chat'.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel and xylographe,

I'll refer only to "Diff since last Save" (not to GIT/SVN).

Let's try to reanalyze it.

In a regular Compare you allow re-Compare even if the files have not been modified.
If the file has *not* been re-saved, you agree there's no reason not to allow a second "Diff since last Save".

If the file has been re-saved...  

> But then the active "Diff since Last Save" will have been cleared, while there are no new diffs to replace it. The actual result will be an implicit "Clear Compare" and a failed "Diff since Last Save". Ideally, the implicit "Clear Compare" should only be performed if the new "Diff since Last Save" will succeed.

Allow me to disagree.
When you first trigger "Diff since Last Save" in a saved file, you get the "Files Match" message.
This would be the **consistent and expected** result if you re-save and re-trigger "Diff since Last Save"; clear and close the temp file.
*Ideally the message should be: `Files Match. Temp file will be closed. Close other file?`.*  

If `File X is saved - operation ignored.` is restored, the message should be: `File X is saved. Temp file will be closed. Close other file?`. 

(Pavel, you suggested to clear and close the temp file if the original file has been re-saved.
We agreed this was "too aggressive". But it's certainly the expected behavior if you save and re-trigger "Diff since Last Save").

> With (2) the outcome might not be what the user intended, yet they cannot go back (undo), because the temp file with the initial save has been removed.

The same is true in a regular Compare. If the user modifies the file(s) and they happen to match, the Compare is cleared. 
***

> This is a problem ATM,
> ...

Very nice. Thank you xylographe.
And, of course, thank you Pavel for fixing it. The index is clever.

Best regards.

**Comment by xylographe** [comment]
Hello Yaron,

> If the file has not been re-saved, you agree there's no reason not to allow a second "Diff since last Save".

Unnecessary, because temp-file == last-save (unless there has been an external modification).

> When you first trigger "Diff since Last Save" in a saved file, you get the "Files Match" message.

Indeed, that is a little odd, "No change since Last Save - operation ignored" would be better, but also increase complexity of implementation.

> The same is true in a regular Compare. If the user modifies the file(s) and they happen to match, the Compare is cleared.

The difference is that the temp file created by the initial Diff will be removed, which makes the *implicit* clear-compare an irrevocable step.

**Comment by Yaron10** [comment]
Hello xylographe,

> If the file has not been re-saved, you agree there's no reason not to allow a second "Diff since last Save".
> 
> Unnecessary, because temp-file == last-save (unless there has been an external modification).

This is indeed unnecessary. 
But it should be consistent with Compare. Do you think CP should monitor whether the file(s) have been modified and not allow re-Compare in case they haven't?

> When you first trigger "Diff since Last Save" in a saved file, you get the "Files Match" message.
> 
> Indeed, that is a little odd, "No change since Last Save - operation ignored" would be better, but also increase complexity of implementation.

We all agree that `File X is saved  - operation ignored.` is better but, as Pavel has mentioned, this can not currently be implemented reliably.

> The same is true in a regular Compare. If the user modifies the file(s) and they happen to match, the Compare is cleared.
> 
> The difference is that the temp file created by the initial Diff will be removed, which makes the implicit clear-compare an irrevocable step.

True. Would you prefer `Temp file will be closed if the files match. Continue?`?
Pavel, what do you think? 

BR

**Comment by Yaron10** [comment]
Hello again,

Not allowing a second "Diff since Last Save" would make this feature "not complete" on its own.

Modify a saved file.
Diff since Last Save.
Modify again.

At this point "Diff since Last Save" is certainly legit and useful. You can use Compare but why make "Last Save" depend on it?

Theoretically a user may find "Diff since Last Save" his main usage of CP and have a toolbar button for this command and not for Compare.
I know this isn't very likely. I meant to illustrate the importance of the command's wholeness and independence.

Thank you.
BR

**Comment by xylographe** [comment]
Hello Yaron,

A *re*-diff-since-last-save is only useful if last-save has changed

> Modify a saved file.
> Diff since Last Save.
> Modify again.

This would be a re-compare, because temp-file and last-save are identical. Clearing the current "Diff since Last Save" and creating a new temp-file that will be identical to the old temp-file, is just an expensive nop.

(1)
Modify a saved file.
Diff since Last Save.
Modify again.
Save modified file.
Modify again.
Diff since Last Save.

Here the temp-file != last-save, therefore "Diff since Last Save" would make sense.

(2)
Modify a saved file.
Diff since Last Save.
Modify again.
Save modified file.
Diff since Last Save.

Again temp-file != last-save, but because there were no modifications since Last Save, the "Diff since Last Save" will fail. Most likely the user accidentally triggered "Diff since Last Save" (perhaps, they intended a re-compare), but because an implicit "Clear Compare" has deleted the temp-file there is no way back. This can be avoided by requiring an *explicit* "Clear Compare".

In case (1) a re-diff with implicit clear-compare would be slightly more convenient (one shortcut) than requiring an explicit clear-compare first. In case (2) a re-diff with implicit clear-compare would be rather annoying due to irreversibility of the implicit clear-compare.

In an earlier comment I wrote "ATM I'm not sure which of these two I prefer." I'm afraid, that indecisiveness has not yet changed. :)

**Comment by xylographe** [comment]
Hello Yaron,

Sorry, I overlooked a previous comment.

> Do you think CP should monitor whether the file(s) have been modified and not allow re-Compare in case they haven't?

This is impossible (external modification). And, besides, no harm will be done when re-comparing the same (unmodified) files.

> True. Would you prefer Temp file will be closed if the files match. Continue?

Not really, because the default button would have to be **No**.
Just pressing `Alt-Shift-D` ("Clear Compare") + `Alt-L` ("Diff since Last Save") is more efficient.

**Comment by pnedev** [comment]
Hello guys,

I'll read your posts when I have more time.

My opinion on this is:

I think there is no harm in making repeatable diff commands. I don't think that something will be lost by doing so - just kind of refresh.
Having said that, it is not completely necessary as the user can do it by clearing the compare and redoing the diff.

Thanks.

BR

**Comment by Yaron10** [comment]
Hello xylographe and Pavel,

xylographe,

Thanks for clarifying your opinion.
You've raised some good points but I still think that consistency with Compare and the wholeness and independence of the Diff commands are more important.

Regarding deleting and recreating the temp file:
I don't know how this is implemented but theoretically the file does not have to be deleted on re-Diff.
This is a question to Pavel.
***
Pavel,

We'll be waiting patiently. :)

Thank you. 

BR

**Comment by pnedev** [comment]
Hello Yaron,

> but theoretically the file does not have to be deleted on re-Diff

Yes, that's absolutely true.
If I implement diff redo the temp file will simply be reused.

No much time, I will come to this later, thanks.

BR

**Comment by pnedev** [comment]
Let's continue this is issue thread #80.
Thank you.

BR

**Comment by pnedev** [comment]
Hello guys,

A final post here: I have adjusted the "Files Match" message depending on the compare type.

The re-diff will be implemented as discussed, the corresponding issue is #80 .

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,


Thank you very much.

BR
