### ISSUE TITLE
General Discussion 3

### ISSUE THREAD

**Issue by pnedev** [pnedev/compare-plugin#89]
Continued from https://github.com/pnedev/compare-plugin/issues/64.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Regarding the crashes I reported some time ago:
I was using the PythonScript plugin and its Console at the time.

> good point - I can confirm this behavior. I got reported that compare plugin failed while
> mine threw an exception.

https://notepad-plus-plus.org/community/topic/11993/wrong-plugin-is-blamed/2

So it's possible that CP was not the culprit. I don't really know.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Yes, it's possible.
Thanks for the update.

BR

**Comment by pnedev** [comment]
Hello all,

I've just added some new settings. Please delete your old _Compare.ini_ file if you update.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the new settings. A nice addition.
I appreciate your work.

Three minor comments.

1) Are you still planning to disable Prev/Next if "Wrap Around" is unchecked?

2) What do you think about the following order?
```
"Warn about encodings mismatch"
"Wrap around results"
"Go to first diff after re-compare"
"Compact navigation bar"
```
This is the sequence of events (and the NavBar is not displayed by default). 

3) `Wrap around diffs` or `Go to first result after re-compare`?

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the feedback.

1) I'm not planning to disable Prev/Next - at least not for now. I don't have much time recently besides it is a minor thing that doesn't affect functionality at all.
2) Looks good, I'll change the order as you suggest.
3) _Wrap around diffs_ seems OK.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Done, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> it is a minor thing that doesn't affect functionality at all.

Indeed.

> Done, thanks.

Thank you very much. I appreciate your time.

BR

**Comment by pnedev** [comment]
Hello all,

Could you please try the latest master branch commit (https://github.com/pnedev/compare-plugin/commit/8c05f333b77607d480ec38b1c068c85d8ec78719) and tell me if it is convenient for you?

I have implemented kind-of dynamic compare views synchronization. It uses the current caret line as focus for views synchronization. This way if you would like to edit a changed line (or simply want to view its compared twin) all you need to do is move the caret to that line and both are automatically aligned.

Thanks for the feedback.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for this improvement too.
I'm sure it's great but unfortunately I don't understand it. :)
Could you please enlighten me?

BR

**Comment by pnedev** [comment]
Hello Yaron,

No problem, I'll illustrate this.
Get your latest [example files](https://github.com/pnedev/compare-plugin/files/447877/prefs.zip) from #51.

Compare them with the old plugin version, the original file is _prefsFFbackup.js_.
Now you are at the first diff. Go to next diff until you reach line 85. Does it look properly aligned?

Now use the latest plugin version and do exactly the same. You should be able to see the difference.
From this point you can also try the following:
Scroll the view so line 78 is fully visible in both views. Then click on line 79. Then on line 78. Then on line 85. This should give you an idea of what the latest change does.

Thanks,
BR

**Comment by Yaron10** [comment]
Hello Pavel,

I still don't get it. Let's try with some screenshots. :)

Is the issue relevant in Top/Bottom or only in Left/Right?
Does it depend on the window width?
Do you mean this?

![InsertText](https://s17.postimg.org/qio228gqn/image.png)

I get the same result with the new version. 

The only difference I've noticed is the following:
Left/Right layout.
Compare.
Press "Next".

Result:
With the new version - lines 16 are not aligned.

![InsertText](https://s17.postimg.org/sg391881b/image.png)

Thanks again. I appreciate your patience.

BR

**Comment by xylographe** [comment]
Hello Yaron,

When you position the **caret** at line 16 the lines should align (new version).

**Comment by Yaron10** [comment]
Hello xylographe,

That's correct. I did not observe it.
But with the old version the problem didn't exist at all.

Do you understand the advantage Pavel is referring to?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

The fix affects both Top/Bottom and Left/Right layouts but it is mostly visible (and really makes sense) in the latter.
And yes, the window width has impact on this because it impacts the position where the wrap occurs.

By the "_old plugin version_" I meant CP prior https://github.com/pnedev/compare-plugin/commit/8c05f333b77607d480ec38b1c068c85d8ec78719 commit.

Shortly put, what the "enhancement" does is align the line numbers where the caret position is (if that line is visible on the screen). IOW if line X is visible on the left and you move the cursor there, line X on the right is automatically aligned - both appear side-by-side.
Prior to the mentioned commit the alignment was done on the first visible line.

Here is an illustration.

Before the latest commit:

![before the enhancement](https://cloud.githubusercontent.com/assets/6064913/18197090/1a9c601e-70fe-11e6-8da5-d86ebca4f25f.png)

After the enhancement:

![after the enhancement](https://cloud.githubusercontent.com/assets/6064913/18197102/2e4a9c7a-70fe-11e6-89e4-8905f9bdc81a.png)

Please note the cursor position is on line 85 on the left (I have selected one word to make it more visible - the green mark).

As I said before - try moving the cursor across the lines for example to line 78 in the right view:

![after the enhancement - line 78](https://cloud.githubusercontent.com/assets/6064913/18197332/25cb2834-70ff-11e6-9c1c-e6618814000e.png)

Hope that makes things clearer.

BR

**Comment by xylographe** [comment]
Hello Pavel,

I think this enhancement (aligning at the *active* line) is a good compromise when line wrap is enabled.
Obviously, having full (constant) alignment would be ideal, but that might be impossible if left and right view have different width (and, perhaps, inefficient in other layouts).
And, of course, if their are many diffs, making the partly aligned views look messy, it is always possible to (temporarily) disable line wrap.

**Comment by pnedev** [comment]
Thanks @xylographe .

**Comment by Yaron10** [comment]
Hello Pavel,

I finally got it. :)

Being used to the Top/Bottom layout, I switched to Left/Right but with the window width I usually use - lines 85 happened to be aligned with the old version (i.e. prior to the relevant commit) as well. 
I failed to see the issue which existed *in other lines* with my window width.

Well, this is a clever and important improvement. :+1: 
And as xylographe has pointed out - the possible different width of the two views is another major factor (which, obviously, should affect https://github.com/pnedev/compare-plugin/issues/51 as well).

Thank you very much.
***
Hello xylographe,

Thank you for the input.

BR

**Comment by pnedev** [comment]
Thanks for the feedback, Yaron.

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the Progress Bar improvements.

I've tested it with large files and it's much better now. Great work. :+1: 

BR

**Comment by pnedev** [comment]
Thanks Yaron, I'm glad you like it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

There are two seemingly minor issues which affect my workflow to some degree.

The first is tagged "Wontfix" and the second is in a closed issue.
Would you mind if I asked you to shortly re-discuss them?
(Whenever you have some free time and it doesn't disrupt your current work).

Thank you very much.
BR

**Comment by pnedev** [comment]
Hello Yaron,

Yes, no problem. Feel free to write your concerns anytime. I'll answer as soon as possible.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you. I appreciate your kindness and patience.

The [first](https://github.com/pnedev/compare-plugin/issues/66#issuecomment-257591567) and the [second](https://github.com/pnedev/compare-plugin/issues/95#issuecomment-257591847).

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll reopen the issues just as a reminder and I'll have a look as soon as I have time.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I do appreciate it.

BR

**Comment by pnedev** [comment]
Hello all,

With the latest commit https://github.com/pnedev/compare-plugin/commit/dca2a7ff9f42a0250ffc5d450d616267efd6b622 I have fixed a lot of compare algorithm problems. However, I had to remove the _Ignore End of Lines_ compare option due to some side effects that were difficult to circumvent. I hope that option was not crucial to anybody.

P.S.
I have also changed the _Compare.ini_ name to _ComparePlugin.ini_.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the recent improvements. Highly appreciated.

Personally I don't mind the removal of `Ignore End of Lines`.

May I ask what you mean by "Compare operation now gives completely identical results no matter which file is considered to be the new and which the old one."? (https://github.com/pnedev/compare-plugin/commit/dca2a7ff9f42a0250ffc5d450d616267efd6b622).

BR

**Comment by pnedev** [comment]
Hello Yaron,

Well, the compare results should be irrelevant of which file is considered new and which - old - only the + / - marks should change. Up to now this was not the case. For each of your compared files A and B you can try to do the compare twice - selecting A as first and next - selecting B as first. That should illustrate the problem. If not write back and I'll send you a pair of files.

You can also try the following when comparing A and B:
1) Select A's whole text and replicate it 10 times (the replication number is not that important actually). The idea is to have file A containing several times its initial text (each copy after the previous).
2) Select A as first and compare to B.
3) Select B as first and compare to A.

You will notice that the results differ (including their arrangement).
If A and B are relatively big files (lets say those are 1200 lines or so) and contain many diffs you'll also notice that the compare process takes different amount of time in case 2) and in case 3).

Hope that clarifies, thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

My reaction after testing those issues was mumbling to myself a sequence of phrases like "Wow!" and "Absolutely brilliant!".
And also: "How come I didn't notice that before?" :)

I think I have mentioned this in the past: you are a one-man-team. And your team is most certainly smart and clever. :)
**5 stars and a standing ovations.** 

Thank you very much.
***
Flipping the files, I've just found another related bug in the old implementation (diff in line 78).

![InsertText](https://s4.postimg.org/5tviv91ul/old_CP.png)
***
Best regards.

**Comment by pnedev** [comment]
Thank you, Yaron,
I'm glad you appreciate it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

A final touch-up before the upcoming official release:

1) [This](https://github.com/pnedev/compare-plugin/files/658230/icon_warning_16.zip) Diff image's level of brightness is slightly closer to the other diff icons.

2) Do you use the current default color settings?
If not, how about setting yours as the default values?
Or mine?

```
[Colors]
Added=14286809
Removed=14145535
Changed=10020839
Moved=16770764
Highlight=427007
Alpha=100
```

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

1. The new diff symbol image is better in terms of contrast which is great, thanks!
2. Yes, I was using the default color settings. I like them because they have good contrast. But yours seem also nice and they are less 'intrusive' so I'll use them as default for the new CP release. Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. Thank you.
Had I known you liked the previous color settings I wouldn't have brought it up.

And congratulations again. :)
Just curiosity: any reason you haven't announced the new release on NPP forum yet?

BR

**Comment by pnedev** [comment]
Hello Yaron,

I thank you.

> Just curiosity: any reason you haven't announced the new release on NPP forum yet?

Time constraint :)
I'll do it now.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

The Champagne is ready. :)
I'm looking forward to it.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Just seen it. Excellent! 👍 

Thank you for the kind acknowledgment.
And I do apologize for the "several tough discussions". I appreciate your patience. :)

I'd like to collect my thoughts and I'll respond on the forum later.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I thank you too for the kind words.
Wish you all the best!

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for 2016. :)
And I wish you a Happy New Year!

**Comment by pnedev** [comment]
Hello Yaron,

Thank you.
Happy New Year to you and your loved ones!

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much for https://github.com/pnedev/compare-plugin/commit/cbfb52311a71564cde8bfe390bab6dbe9e4a2f71. Very nice and useful. 👍 
***
The Plugin Manager does not notify users of the new version.
Does that mean the list is not yet updated? - In the "Available" tab v2 is listed.
And "Compare" in the "Installed" tab vs. "ComparePlugin" in the "Available" tab?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

You are welcome, thanks.

> Does that mean the list is not yet updated?

Most probably yes.

> In the "Available" tab v2 is listed.

That is because you have Compare v2 installed. I suppose Plugin Manager reads the version number of installed plugins from their corresponding DLLs. Try moving the CP DLL to _plugins/disabled_ folder and check again. This time Compare should be in the _Available_ PM tab and.... yes, I just tried it - the version is 1.5.6 meaning the list indeed is not yet updated.

> And "Compare" in the "Installed" tab vs. "ComparePlugin" in the "Available" tab?

What is yours PM version?
Mine is 1.4.3 and the plugin is _Compare_ in both tabs.
This might come from the fact that I renamed the DLL to _ComparePlugin_ and the name in the PM list (the old one) is _Compare_.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> You better use 8d3574e.

Great. Thank you.

My PM version is also 1.4.3.
In the PM settings I have the options "Show unstable and development..." checked and hence the difference.

Anyway, the vast majority of CP users have probably not updated to v2.0 yet.
They don't know what they're missing. :)

Thank you.
BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the new features "Compare Range" and "Dynamic Compare".
Both are brilliant ideas. "Dynamic Compare" is quite ambitious. :) 👍 

I haven't yet thoroughly tested them.
Allow me to share some initial thoughts.

**Compare Range**

Using bookmarks as the "range setters" has indeed some advantages.
OTOH, the user may have multiple bookmarks along the file and removing/adjusting them might be complex and even tedious.
Another minor con: some users prefer not to display the Bookmarks Margin.

How about Compare Selections? - Compare the *main* selections in both files.
I think this would be easier and much more intuitive. 

If there are not selections in both files (e.g. only one file has a selection), I'd prompt "No Selections to Compare."
Comparing a range in file A to the entire file B is more flexible but might be misleading in real life:
you want to compare function `func()` in file A to `func()` in file B and might forget to select it in either file.

Progress Bar: "Comparing selection in file A vs. selection in file B...".

Match: "Selections in file A and file B match.". 
I'm not sure if "Closed compared files?" is relevant here.

In Firefox I use a single toolbar button for several related actions (left-click, right-click etc.).
Would it be possible to assign right-click-Compare to Compare Range/Selections?
This may save advanced users adding another button to the toolbar. 

**Dynamic Compare**

In some cases the Progress Bar should be used, correct?

Could you please try deleting an "added line" in file A?
Currently an empty line is inserted in file A and a "removed line" is inserted in file B.

Thanks again for the new gems. I was highly impressed.

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for your valuable feedback, I appreciate it.

Those are features that are still in development and I expect them to have problems. They are currently introducing issues with blank lines handling during re-compares and are also clearing the 'undo' list way too often (which is not exactly a problem but is VERY undesirable). I know about those shortcomings and I'm currently trying to fix them.

Because of the above you will probably stumble upon many strange cases like

> Currently an empty line is inserted in file A and a "removed line" is inserted in file B.

I agree with all your thoughts and comments about **Compare Range** and the **Compare Selections** you propose is indeed much clearer from user perspective. So I have made the corresponding code modifications - you can find them as https://github.com/pnedev/compare-plugin/commit/dae630dab3dc8f9489157c06c492bae3fc732689 and the builds - here:

- x64: https://ci.appveyor.com/api/buildjobs/asi9ubfwsru4mckc/artifacts/ComparePlugin.dll

- x86: https://ci.appveyor.com/api/buildjobs/1b3kxq9bxyfv3sud/artifacts/ComparePlugin.dll

The only thing I disagree with is

> Would it be possible to assign right-click-Compare to Compare Range/Selections?

I'm not sure I can even intercept the toolbar right-click action but beside that I think one more icon is more clear, visible and user-friendly. Just another shortcut is also quite OK IMO.
Do you think that adding a new toolbar icon would be misleading?

> In some cases the Progress Bar should be used, correct?

I'm not planning to use the Progress Bar during the dynamic auto-update. Yes, if one is changing a big portion of the file that might be useful but I cannot know for sure when to show the progress and when not. That's because the time it takes to re-compare depends on the number of diffs found which is not predictable. I can try to wild-guess the re-compare time required (and the need for the progress bar respectively) based on the re-compared section size but that will be very inaccurate and sub-optimal.
I think the delay will rarely bother the user as in most cases he will not be changing big portions of the file at once. The only exception to this is probably when reloading the file (which will trigger a whole file re-compare).

Thanks.

BR

**Comment by pnedev** [comment]
Hello again Yaron,

> I'm not planning to use the Progress Bar during the dynamic auto-update.

I might reconsider that and show progress only when the changes span multiple lines. Single line change will re-compare without progress as the user might just be typing and must not experience noticeable delays.
Tell me what you think, thanks.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> I might reconsider that and show progress only when the changes span multiple lines.

I have implemented that in
https://github.com/pnedev/compare-plugin/commit/6cd2c63d3432ae23945d5a8c764665741323eb55.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much for your work. Absolutely great.

**Compare Selected Lines**

Better than "Compare Selections". :)
This feature seems quite "baked", isn't it? I think it would be very useful.

1) If you Compare Selected Lines in Single-View mode and there are no selections in both files - you get the files in Double-Views and then the "operation ignored" message is displayed.
Wouldn't it make more sense to display the message without moving to Double-Views?
I think the behavior should resemble Compare with only one file and not Match.

2) 
> Match: "Selections in file A and file B match.".
> I'm not sure if "Closed compared files?" is relevant here.

May I change my mind? - I do apologize.
This option can actually be useful in this case as well. What do you think?

3) Ctrl+Alt+R is used by NPP. How about Ctrl+Alt+N?

4) This feature is definitely a "button worthy" (Seinfeld: "Sponge Worthy" :) ).
Could you please have a look at [these images](https://cloud.githubusercontent.com/assets/10229320/22450655/d9477ace-e770-11e6-86f1-a442746981e8.png)? I'm not very happy with either of them but I find it hard to illustrate both "Selection" and "Compare". Any idea? 

(There seems to a problem with uploading ZIP files at the moment. Please rename the PNG extension to ZIP).

**Dynamic Compare**

> In some cases the Progress Bar should be used, correct?
> ...
> I have implemented that in 6cd2c63.

Great! Thank you.

As I've mentioned, this experimental feature is an ambitious experiment. :)
Could you please let me know when it gets to a "testing stage"?

Best regards.

**Comment by pnedev** [comment]
Hello Yaron,

Let me comment point by point:

1. It will complicate things a bit but you are right, I agree.

2. I personally don't find that option useful at all even in the original case thus I'll trust your judgement.

3. Hm, I thought I changed that to Ctrl+Alt+L (from _Line_) but I don't mind using Ctrl+Alt+N as well.

4. Thank you for the new bitmaps. I also think they are a bit unclear though. I have changed your original _Compare.bmp_ a bit to use it as _CompareLines.bmp_. Please have a look at the latest commit (pointed below) and tell me how you find the new image.

I have done the changes required in regard with the points above. The commit is https://github.com/pnedev/compare-plugin/commit/156e6fb654c859d4e4385ced7274a7041da1a7e7.

Binaries are

- x64: https://ci.appveyor.com/api/buildjobs/u369y2oj34xmcupj/artifacts/ComparePlugin.dll

- x86: https://ci.appveyor.com/api/buildjobs/h0ere77jp3p7cgyd/artifacts/ComparePlugin.dll

Please test and tell me what you think.

> Could you please let me know when it gets to a "testing stage"?

I will, sure. It will take a while before I get to that point.

Thank you for your feedback, testing and for the bitmaps. I appreciate it as always.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the recent changes. I do appreciate your work and patience.

With your permission, some more comments.

**Re-Compare Selected Lines - No Selections**

Literally - there are no selections and the operation should be ignored.
However, both in terms of concept and practically it may not be the desired behavior. 

Concept: the selections are mere "range setters" and we do have a range - the previously selected lines.
Practically: the user compares `funcA()` in two files, makes some changes in that section and wants to re-Compare (Selected Lines). Why not allow that without re-selecting?

If the original range (e.g. lines 20-30) doesn't exist anymore, the operation should be ignored.
And if the original range only partially exist?
Is this getting too complex and it's better keep the current behavior?

**Re-Compare Selected Lines - With Selections**

We can't really know if the user wants to add another range or set a new range and clear the previous one.
I tend to think that the latter approach would be better. Regard the new selections as new files to compare.
What do you think?

**Images**

Please don't mind my writing this but your version is not very illustrative/clear either. :)
I've added a line to the window which gives me an extra pixel.
The dotted frame is quite common in illustrating a selection. The red and green lines are slightly darker.
If you find the result adequate, I'll modify the other images too.
And what do you think of Compare2? 

Again - I can't upload ZIP files, can you?
![Images](https://cloud.githubusercontent.com/assets/10229320/22486215/4901ca72-e811-11e6-9803-4a0ff18c31b6.png)

**Shortcut**
Ctrl+Alt+R is still there. Ctrl+Alt+L is also used by NPP which leaves us with "N" (Line, Number).
***

> Could you please let me know when it gets to a "testing stage"?
> ...
> I will, sure. It will take a while before I get to that point. 

Thank you very much and best of luck.

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Literally - there are no selections and the operation should be ignored.
However, both in terms of concept and practically it may not be the desired behavior.

> Concept: the selections are mere "range setters" and we do have a range - the previously selected lines.
> Practically: the user compares funcA() in two files, makes some changes in that section and wants to re-Compare (Selected Lines). Why not allow that without re-selecting?

IMO this will be more confusing. The command is _Compare Selected Lines_ and this is what it should do. It would be unexpected (at least for me) if on re-compare without selection something happens. Besides, I might have completely forgotten about the previous selection.
If you are comparing two functions and you make changes then the dynamic re-compare on change will take care of the update, there shouldn't be a need for you to trigger re-compare manually.
This was about the practicality of remembering selections and this is indeed arguable and a matter of preference.
On the other hand is the technical challenge of implementing this. The user selection will not be valid after the compare because of the line alignments. There will probably be offset applied and change in length also. Then if the user deletes part of the selection (or the whole) but the lines below are enough the previous range would exist but be totally different part of the file which means a smart handling of the deletion needs to be implemented and the deletion is already quite complicate (and will probably be even more so in the future because of some changes I'm planning to implement).

> We can't really know if the user wants to add another range or set a new range and clear the previous one.
I tend to think that the latter approach would be better. Regard the new selections as new files to compare.
What do you think?

The reason I decided to implement a range re-compare was to provide a way for setting a manual synchronization point. Of course it is also useful for re-comparing selected ranges but in any case that is actually the same operation as _Compare Selected Lines_ - it will simply keep the current compare results outside the selections.

> Please don't mind my writing this but your version is not very illustrative/clear either. :)

I like it because it resembles selection but OK, no problem :)

> The dotted frame is quite common in illustrating a selection. The red and green lines are slightly darker.
If you find the result adequate, I'll modify the other images too.

Well, _CompareLines.bmp_ looks fine even without updating the other bitmaps - take a look at commit https://github.com/pnedev/compare-plugin/commit/2a5e83a886b270907001603cc8ea19c824932ef0.

Another idea - what do you think about using the same bitmap as Compare but adding some mark in the right-down corner suggesting 'Lines Compare' (just like we have a mark in _ClearCompare.bmp_)?

> And what do you think of Compare2?

I personally prefer the current icon because it looks like two views side by side (which resembles compare operation more IMO).

> Again - I can't upload ZIP files, can you?

I haven't tried but I suspect I won't be able to do that too.
Have you tried making a zip with a password? If that doesn't help then it is probably some kind of filter blocking archives.

> Ctrl+Alt+R is still there.

Hm, are you sure you haven't set that in your personal N++ _shortcuts.xml_? Open it and search for _ComparePlugin.dll_. Delete all rows containing that to reset your manually set CP related shortcuts then save the xml and restart N++. Then you should see Ctrl+Alt+N.

Thank you Yaron for all the feedback, suggestions and for the bitmaps too.
Those are really helpful :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> IMO this will be more confusing. The command is Compare Selected Lines and this is what it should do.
> ...

Good points. And it's more complex than I thought.
Thank you.

> We can't really know if the user wants to add another range or set a new range and clear the previous one.
> I tend to think that the latter approach would be better. Regard the new selections as new files to compare.
> What do you think?
> ...
> The reason I decided to implement a range re-compare was to provide a way for setting a manual synchronization point. Of course it is also useful for re-comparing selected ranges but in any case that is actually the same operation as Compare Selected Lines - it will simply keep the current compare results outside the selections.

I'm afraid I wasn't clear enough.
If the users Compare (Selected Lines) lines 10-20 and then selects lines 30-40, why keep the diffs for lines  10-20?
This is related to the previous point: if the previous selection is gone and forgotten ("Besides, I might have completely forgotten about the previous selection."), I think we must regard the new selection as "Clear previous selection Compere and Compare new selection.".
It's also confusing: after re-Compare you go the first diff in lines 10-20. 

If you agree, this should be the behavior in (regular) Compare and re-Compare Selected Lines: Clear previous Compere and Compare new selection.

Another minor point: if you Compare Selected Lines *without selections* and the files' encoding is different - I think the message should be "... - operation ignored." without the encoding warning. 

**Images**

> Another idea - what do you think about using the same bitmap as Compare but adding some mark in the right-down corner suggesting 'Lines Compare' (just like we have a mark in ClearCompare.bmp)?

That's a good idea. I've tried that but the result wasn't really good.
I've modified the other images so that they all have the same size and color.
May I ask you to replace them all (including CompareLines.bmp)? Thank you.

![Images](https://cloud.githubusercontent.com/assets/10229320/22527702/cf391d8a-e8d8-11e6-99a2-5fcdc8170dee.png)

Still a problem with ZIP files. Thanks for the possible explanation.

**Shortcut**

> Hm, are you sure you haven't set that in your personal N++ shortcuts.xml?

Sorry, my mistake. I forgot I'd been looking for a free shortcut.
***
Thank you for your great work. Highly appreciated.

> Thank you Yaron for all the feedback, suggestions and for the bitmaps too.

My pleasure! :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

> I'm afraid I wasn't clear enough.
If the users Compare (Selected Lines) lines 10-20 and then selects lines 30-40, why keep the diffs for lines 10-20?

Thanks for clarifying.
Well, this is exactly what I'd like it to do. This way you can 'aggregate' several partial compares. The new selection compare clears only the range that is re-compared. If you make full compare and then do selection re-compare in order to set manual synchronization point then the previous diffs should remain and not be cleared. You can then set again manual synchronization point below the previous and again you won't loose your previous diffs.

> Another minor point: if you Compare Selected Lines without selections and the files' encoding is different - I think the message should be "... - operation ignored." without the encoding warning.

Good point. I have implemented that and as addition now encoding check is done only when the compare is new. On re-compare there is no point to warn about encoding - the user already knows that there is a mismatch and has agreed to proceed with the comparison.

> I've modified the other images so that they all have the same size and color.

OK, great! I have updated the images, thanks for providing them.

BR

**Comment by pnedev** [comment]
Hello again, Yaron,

I just would like to thank you for your kind and generous donation.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> Well, this is exactly what I'd like it to do. This way you can 'aggregate' several partial compares.

Thanks for the explanation.

When I first referred to this issue, I thought both approaches were legit.
But if you take "Compare SL" literally and not allow re-Compare SL without selection (i.e. based on the previous selection; and let's leave aside the complexity), I think it would be consistent to take the command literally in this case as well. Namely: Compare SL *only*.

Well, we know we interpret "consistency" slightly differently. :) 

> I have implemented that and as addition now encoding check is done only when the compare is new. On re-compare there is no point to warn about encoding - the user already knows that there is a mismatch and has agreed to proceed with the comparison.

> ...
> I have updated the images,

Great. 👍 
Thank you.

> I just would like to thank you

I'm truly grateful for your amazing work, and I do feel you deserve much more.
I wish I had more "symbols". :)

BR

**Comment by pnedev** [comment]
Hello Yaron,

> Well, we know we interpret "consistency" slightly differently. :)

:) This might be the case as well :)

Here's my view:

Why would re-comparing SL be inconsistent this way? It does re-compare the selections only. It simply leaves the history behind (doesn't clear the whole previous compare results). And its name doesn't imply clearing the old results. I may add another setting about this but is it really necessary? If the user would like to do a complete new selection compare he can always clear the compare results first. If we clear that instead of him it is as if we are doing two commands in one - ClearCompare  + CompareSL which doesn't add anything new. I agree the other might be very tricky and is currently not working at its best. And it is of course for advanced usage (one might screw his compare results). I hope I'll find enough time soon to look for an appropriate compare sample to illustrate the usefulness of the current implementation (and what I had in mind when doing it like this).

> I wish I had more "symbols".

Your precise and insightful feedback is more than enough, thank you.

BR

**Comment by pnedev** [comment]
Hello Yaron,

Here is a small and pretty simple sample to illustrate my idea behind SL re-compare without clearing old results.

1) Get this files: [cmp_sample.zip](https://github.com/pnedev/compare-plugin/files/750863/cmp_sample.zip) (hm, no problem uploading zip on my side).
2) Make full compare.
3) Now you might notice that diffs at lines 30-33 are not compared the best way they could be.
4) Select lines 31-33 in the new file and lines 30-33 in the old. Do SL re-compare.
5) Now the results 31-34 look clearer (except for line 30 in the new file that was simply not compared but the blank line 30 in the old file marks that) and all other diffs below remain intact so you can comfortably 
inspect all diffs at once.

As I said before this is an advanced usage and the user needs to pay attention and be aware of what he is doing in order not to screw his results (which is something I cannot fully prevent because of the nature of the feature). But, you know - with freedom comes responsibility.

Tell me what you think. Thanks.

BR

**Comment by pnedev** [comment]
Hello again Yaron,

Here is another sample:

1) Get files [cmp_sample_2.zip](https://github.com/pnedev/compare-plugin/files/750954/cmp_sample_2.zip).
2) Switch off _Ignore Lines_ option for clarity. Switch off _Detect Moves_.
3) Make full compare.
4) Go to line 143. Now you might notice that the results are not presented the best way.
5) SL re-compare lines 147-150 in the new file and lines 145-150 in the old one. Again, the diffs presentation is much clearer now.

You can repeat the same process with _Detect Moves_ switched on but then you'll need to do double SL re-compare - first, to instruct CP that restoreNoActivate() function in the old file needs to be compared to restore() function in the new one and second - to fine-tune the compare inside the function body (as in the example above).

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the explanation and the examples. It makes things clearer.

There's something more fundamental I missed in your implementation.
I thought Compare SL should resemble coping the selections in files A and B, pasting them in New1 and New2 respectively and comparing.

Shouldn't this be the approach?
*cmp_sample.zip*
Select lines 31-33 in the new file and lines 30-33 in the old. Do SL re-compare.

Why should the diff status in line 30 (new) be removed? Why a blank line 30 in the old file?
Line 30 in the new file is out of range.
I'd expect these results:

![InsertText](https://s29.postimg.org/h6v7qn05z/image.png)

This is also my first case in https://github.com/pnedev/compare-plugin/issues/107.
And now to my second case in https://github.com/pnedev/compare-plugin/issues/107, and with the files in *cmp_sample.zip*:

STR:
Make full compare.
Select lines 31-33 in the new file and lines 30-33 in the old. Do SL re-compare.
Select lines 30-34 in both files and re-Compare SL.
Clear Compare.

Result:
Line 30 in the old file is empty/blank.

And even regardless of this issue, it seems that allowing re-Compare SL with blank lines might lead to a total mess (think about multiple re-Compare SL with blank lines).

Checking if the new range contains blank lines or not is probably complex too.
Therefore - IMO it would be much better to have this great feature "Compare SL" in a simple and less flexible form but also less prone to unexpected results.
And that is to say: allow Compare SL only in non-compared files.

If you agree, our former discussion would be irrelevant.
If you don't...

> Why would re-comparing SL be inconsistent this way? It does re-compare the selections only. It simply leaves the history behind (doesn't clear the whole previous compare results). And its name doesn't imply clearing the old results.

This is a good argument. And I thought about it too. 
Literally - you're right: "It does re-compare the selections only.".
If the command was still Compare Range (by Bookmarks), would you allow re-Compare Range based on the *still existing* bookmarks? - The implementation complexity would be the same.

If not - the user understands that the previous range is not valid anymore.
So why keep the invalid results on re-Compare? It's true that you don't *actively* do anything but, in terms of concept, passively keeping them is not that different. 

Another major point:
Before you brought up the beautiful examples, I thought about two possible reasons for using Compare SL in already compared files instead of full re-Compare.
1. The user is concentrating on a specific section in very large files and wants to avoid the lengthy full re-Compare (quite weak).  
2. The user is concentrating on a specific section and wants the *first and last* diffs to be the first and last in that section (major).

If you don't clear the previous full Compare results, why would you use Compare SL after a full Compare in real life?

And yet another point:
Compare and Compare SL are two different commands.
If the user initiates Compare SL, I think it means: now I want this type of Compare and not the other.

Well, that's my view. :)
If you don't agree, I think that an extra setting for that would indeed be too much. 

Thank you very much. I do appreciate your work.
***
> Your precise and insightful feedback is more than enough, thank you.

Thank you. You are a gentleman.

BR

**Comment by Yaron10** [comment]
Hello again Pavel,

The more we discuss it, the clearer it becomes.

Most of the points we've discussed are debatable.
I'm pretty sure though of the following:
Multiple Ranges are Multiple Compares.
Allowing to compare two ranges and jumping to the first diff of the first one (10-20, 30-40) would be like comparing A and B, then B and C and always activating A.

A possible solution might be setting the realm of the navigation commands according to the caret position.
Is it worth it?

Another possible option is actually opening the selections in two new (temp?) files.

What do you think?
***
Just curiosity:
Why did you change `#include "icon_sub_16.h"` to **17**?

Thanks again and have a nice weekend.

**Comment by pnedev** [comment]
Hello Yaron,

Thank you for the comments.
I didn't have time to write during the weekend.
This thread is becoming lengthy - let's continue in https://github.com/pnedev/compare-plugin/issues/108.

BR
